# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Project Zen' do
pod 'Onboard'
pod 'Parse'
pod 'Facebook-iOS-SDK'
pod 'ParseFacebookUtils'


end

target 'Project ZenTests' do
pod 'Parse'
pod 'Onboard'
pod 'Facebook-iOS-SDK'
pod 'ParseFacebookUtils'

end

